### ISSUE TITLE
Individual settings for TNT Suggestion

### ISSUE THREAD

**Issue by MysteryTimeTrav** [MrMicky-FR/UltimateTNT#10]
Hi, is is possible to have a feature where renaming TNT in an anvil gives it different settings so that the changes aren’t uniform across all TNT?

Asking because it could be good to have it so that there’s different TNT types for dispenser based TNT cannons like Propellant or Projectile where TNT renamed “Propellant” can have a short fuse while “Projectile” would have a long fuse so it doesn’t airburst on high angle shots.

**Comment by 88HeilHitler** [comment]
such a cool suggestion, but it has not yet been implemented...

**Comment by MrMicky-FR** [comment]
Hi, this would require to almost recode the plugin from scratch, so it’s not planned for now, but I’ll accept a pull request for this

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
