### ISSUE TITLE
Place cooldown

### ISSUE THREAD

**Issue by Jeroen123TC** [MrMicky-FR/UltimateTNT#11]
Can you add a tnt place cooldown, so players must as example wait for 3 seconds befor the can place another tnt.

for questions you can contact my on discord: Jeroen123#1025

and if you added this option do you want to tag me in discord of dm me?

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
