### ISSUE TITLE
TNT Chunk Loader

### ISSUE THREAD

**Issue by MysteryTimeTrav** [MrMicky-FR/UltimateTNT#12]
Basically, for TNT cannons when they're fired into unloaded chunks with the current vanilla features become suspended in mid air as well as their fuses and only fall when the chunks load in. Is it possible for a feature in which TNT launched at a high velocity could load the chunks as they pass through it in order to make long range artillery viable? (only fast moving ones prolly should be used in order to prevent players from making TNT chunk loaders by just dispensing stationary TNT)

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
