### ISSUE TITLE
Obsidian breaker cooldown

### ISSUE THREAD

**Issue by DenisJ9798** [MrMicky-FR/UltimateTNT#14]
**make a setting that if within 10 minutes, five pieces of tnt explode, then there is a breakdown of the obsidian**

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
