### ISSUE TITLE
Bug avec la version.

### ISSUE THREAD

**Issue by TheIntelloBox** [MrMicky-FR/UltimateTNT#2]
Yop,

J'ai installé la dernière version sur Spigot et je l'ai mise sur mon serveur, or, dans la console ça me dit que j'utilise la version 1.7.1 au lieu de la 1.8. 

Comment je peux régler ça ?
Merci d'avance ! :D

**Comment by MrMicky-FR** [comment]
Ça vient du fait que je m'étais trompé dans les versions lors de la dernière update (la version sur Spigot était la 1.8.0 alors que la version du plugin était la 1.7.1).

Du coup en mettant la dernière version du plugin ça sera bon
