### ISSUE TITLE
Further help required

### ISSUE THREAD

**Issue by Tinfox815** [MrMicky-FR/UltimateTNT#20]
I put the Blocks I wanted on the blacklist from the spigot material list but it still blows them up in game would you show me how its written in config so it will work

Does this work with 1.19?

**Comment by MrMicky-FR** [comment]
Everything should work on 1.19, can you send your current `config.yml` file?

**Comment by Tinfox815** [comment]
#
[UltimateTNT-Copy.zip](https://github.com/MrMicky-FR/UltimateTNT/files/9578339/UltimateTNT-Copy.zip)

I’ve tried several different ways in typing it in I’m just not sure how it works with this plug-in I’m sure it’s a simple fix and I’m glad to have your help

**Comment by MrMicky-FR** [comment]
Hi, you have basic YAML syntax errors which means the plugin can't parse the config. You should check in the server console during startup for errors and/or use a website like https://codebeautify.org/yaml-validator to verify your YAML configuration.

For this time here is the correct YAML config for the blocks:
```yaml
BlacklistBlocks:
- 'DIAMOND_ORE'
- 'NETHER_GOLD_ORE'
- 'GOLD_ORE'
- 'IRON_ORE'
- 'DEEPSLATE_DIAMOND_ORE'
- 'DEEPSLATE_IRON_ORE'
- 'DEEPSLATE_GOLD_ORE'
- 'DEEPSLATE_LAPIS_ORE'
- 'DEEPSLATE_EMERALD_ORE'
- 'DEEPSLATE_REDSTONE_ORE'
- 'DEEPSLATE_COAL_ORE'
- 'NETHER_QUARTZ_ORE'
- 'NETHER_QUARTZ_ORE'
- 'DEEPSLATE_COPPER_ORE'
- 'RAW_COPPER'
- 'RAW_GOLD'
- 'RAW_IRON_BLOCK'
- 'BUDDING_AMETHYST'
- 'DIAMOND_ORE'
- 'NETHER_GOLD_ORE'
- 'GOLD_ORE'
- 'IRON_ORE'
- 'DEEPSLATE_DIAMOND_ORE'
- 'DEEPSLATE_IRON_ORE'
- 'DEEPSLATE_GOLD_ORE'
- 'DEEPSLATE_LAPIS_ORE'
- 'DEEPSLATE_EMERALD_ORE'
- 'DEEPSLATE_REDSTONE_ORE'
- 'DEEPSLATE_COAL_ORE'
- 'NETHER_QUARTZ_ORE'
- 'DEEPSLATE_COPPER_ORE'
- 'RAW_COPPER_ORE'
- 'RAW_GOLD_ORE'
- 'RAW_IRON_BLOCK'
- 'BUDDING_AMETHYST'
- 'COPPER_ORE'
- 'COAL_ORE'
- 'REDSTONE_ORE'
- 'LAPIS_ORE'
- 'NETHER_GOLD_ORE'
```

About the material types, the valid list is available here: https://jd.papermc.io/paper/1.19/org/bukkit/Material.html (without the ones starting with `LEGACY_`)

**Comment by Tinfox815** [comment]
You can actually close this thread you fixed it thank you
