### ISSUE TITLE
TNT Defuse Feature

### ISSUE THREAD

**Issue by Braresa** [MrMicky-FR/UltimateTNT#21]
I was looking for a plugin that makes TNT not so destructible and make them counterable with some type of defusing method, but i didn't find it (only a discontinued plugin made 6 years ago). Can you add this feature? Not something too big, just a way to defuse TNT with a specific item or empty handed, using right click.

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
