### ISSUE TITLE
Add ancient debris

### ISSUE THREAD

**Issue by SuperIsSuper** [MrMicky-FR/UltimateTNT#25]
Hey Micky
first I would like to say that I love UltimateTNT plugin that you made
but you need to add Ancient_Debris so it breaks
like obsidian

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues.

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
