### ISSUE TITLE
Some good ideas

### ISSUE THREAD

**Issue by Myro-Off** [MrMicky-FR/UltimateTNT#26]
Hi !
You should add the fact that we can **add other blocks** which can be **broken several times** like _obsidian_, this will allow us to add the _anvil_, the _ender chest_ or even the _enchantment table_ which **cannot** currently not be exploded.

It would be nice to add the possibility of **modifying the item required** in the hand to throw the tnt, giving the possibility of putting **custom items** like _dynamite_. Don't forget to add the **item data**,  for _textured items_ added with the plugin itemsadder for example.

THANKS

**Comment by MrMicky-FR** [comment]
Hello, since I don't plan to add any new features, I'm archiving this repository and closing open issues. 

This plugin will continue to work as before and can still be downloaded from SpigotMC, but will not receive any updates.
