### ISSUE TITLE
Add obsidian breaker

### ISSUE THREAD

**Issue by TheIntelloBox** [MrMicky-FR/UltimateTNT#3]
Salut !

J'ai un monde Factions sur mon serveur, or, si j'explose les creepers sur de la terre ça marche très bien, mais dès qu'ils explosent sur de l'obsidienne, cela ne fonctionne pas, aucun dégat.
J'ai World Guard mais tout est oké dessus, toutes les explosions sont activées.

Tu peux m'aider ?

**Comment by MrMicky-FR** [comment]
Bonjour, 

C'est peux être simplement car dans Minecraft l'obsidienne n'explose pas ?

**Comment by TheIntelloBox** [comment]
Tu peux ajouter une option pour ça ? :D

**Comment by MrMicky-FR** [comment]
Je vais voir si je peux ajouter ca

**Comment by TheIntelloBox** [comment]
D'accord. :)

**Comment by MrMicky-FR** [comment]
L'option a (finalement) été ajoutée via le commit 809d94fcee253ede184786077f745340e11f7b8a dans la version 1.11.1 disponible sur Spigot 😄

**Comment by TheIntelloBox** [comment]
Merci beaucoup mais je n'ai plus de serveur. xD :D
