### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by TheIntelloBox** [MrMicky-FR/UltimateTNT#4]
https://hastebin.com/ihocimexov.vbs

**Comment by MrMicky-FR** [comment]
Hello,
How I can replicate this error ?
Thanks

**Comment by TheIntelloBox** [comment]
Salut,

J'ai juste ça dans la console, je n'en ai aucune idée. :D 

Bien cordialement,
TheIntelloBox.

**Comment by MrMicky-FR** [comment]
Corrigé dans https://github.com/MrMicky-FR/UltimateTNT/commit/124d182e3f1a8cd30fd87e460fa7d927c8569ce9

(cela venait d'un changement de Spigot sur le BlockDispenseEvent sur les versions 1.11 et +)

Je vais bientôt publier la version corrigée sur Spigot

**Comment by TheIntelloBox** [comment]
Merci beaucoup. :)
