### ISSUE TITLE
1.13 compatible.

### ISSUE THREAD

**Issue by TheIntelloBox** [MrMicky-FR/UltimateTNT#5]
Salut !

https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/

**Comment by MrMicky-FR** [comment]
Bonjour,

Le plugin est déjà compatible en 1.13 (testé en 1.13-pre7).

Après si il y a des bugs merci de me les signaler

**Comment by TheIntelloBox** [comment]
Merci. :)
