### ISSUE TITLE
1.13.1 support

### ISSUE THREAD

**Issue by TheIntelloBox** [MrMicky-FR/UltimateTNT#6]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-1-development-builds.336415/

**Comment by MrMicky-FR** [comment]
Le plugin est déjà compatible normalement, après la pour le moment je n’ai pas la possibilité de le tester. 

Si il y a des bugs en 1.13.1 il suffit de me les signaler :)
