### ISSUE TITLE
Light_gray_shulker_box

### ISSUE THREAD

**Issue by Jeremylo1** [MrMicky-FR/UltimateTNT#7]
Salut, c'est juste pour te dire qu'il y a un problème avec le LIGHT_GRAY_SHULKER_BOX, il est impossible de l'ajouter aux différente whiteliste du plugin contrairement aux autres ...

**Comment by MrMicky-FR** [comment]
Bonjour,
en quelle version est ton serveur ? Car avant la 1.13 le Material `LIGHT_GRAY_SHULKER_BOX` n'existe pas, pour du gris clair c'est `SILVER_SHULKER_BOX `

**Comment by Jeremylo1** [comment]
Salut, mon serveur est en 1.13.1. Et ok pour le SILVER, je vais tester pour
voir.

MErci

**Comment by Jeremylo1** [comment]
Je confirme que avec le nom de SILVER c'est fonctionnelle ;)

**Comment by MrMicky-FR** [comment]
D'accord parfait, du coup je close :)
