### ISSUE TITLE
As soon as I enabled the plugin, Dispensers no longer dispense TNT

### ISSUE THREAD

**Issue by Germanode** [MrMicky-FR/UltimateTNT#8]
As explained in the title. Using 1.12.2 PaperSpigot latest version.

**Comment by MrMicky-FR** [comment]
I tried with the latest Spigot release of UltimateTNT and the latest 1.12.2 Paper build (#1613) and the dispensers correctly dispense TNT. Do you have any errors or warn from UltimateTNT ? And maybe can you try to see if the problem comes from an other plugin

**Comment by Germanode** [comment]
1. There are no errors or warnings in the console. The only thing that happens after I install the plugin is that dispensers act like empty. Doesn't happen if the plugin is not installed. 
2. The dispensers are filled with TNT but they emit an "empty" sound when activated and the particles that come with it.

![2019-06-10_20 27 16](https://user-images.githubusercontent.com/17865871/59217599-9583ca00-8bbe-11e9-8504-799fe650b241.png)

Config: [https://pastebin.com/dZyW80Qc](https://pastebin.com/dZyW80Qc)

**Comment by MrMicky-FR** [comment]
Thanks, it should be fix in the commit above
